//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Template.Ressources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية.
        /// </summary>
        public static string AccountCin {
            get {
                return ResourceManager.GetString("AccountCin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الأب.
        /// </summary>
        public static string AccountFatherName {
            get {
                return ResourceManager.GetString("AccountFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الأول.
        /// </summary>
        public static string AccountFirstName {
            get {
                return ResourceManager.GetString("AccountFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الجد.
        /// </summary>
        public static string AccountGrandFatherName {
            get {
                return ResourceManager.GetString("AccountGrandFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العائلة.
        /// </summary>
        public static string AccountLastName {
            get {
                return ResourceManager.GetString("AccountLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاحية الوصول.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفعل.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة محتوى.
        /// </summary>
        public static string addcontent {
            get {
                return ResourceManager.GetString("addcontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد ترشحت لهذه الدورة.
        /// </summary>
        public static string Applied {
            get {
                return ResourceManager.GetString("Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترشح.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترشح للدورة.
        /// </summary>
        public static string ApplyToPeriod {
            get {
                return ResourceManager.GetString("ApplyToPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المنطقة.
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string CanAdd {
            get {
                return ResourceManager.GetString("CanAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string CanDelete {
            get {
                return ResourceManager.GetString("CanDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string CanEdit {
            get {
                return ResourceManager.GetString("CanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قراءة.
        /// </summary>
        public static string CanView {
            get {
                return ResourceManager.GetString("CanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسباب الرفض إن وجدت.
        /// </summary>
        public static string Causes {
            get {
                return ResourceManager.GetString("Causes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقر الدورة.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المعهد.
        /// </summary>
        public static string CenterName {
            get {
                return ResourceManager.GetString("CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الشهادة العلمية.
        /// </summary>
        public static string CertificationName {
            get {
                return ResourceManager.GetString("CertificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة كلمة السر.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدورات.
        /// </summary>
        public static string CounterCourses {
            get {
                return ResourceManager.GetString("CounterCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الاختبارات.
        /// </summary>
        public static string CounterExam {
            get {
                return ResourceManager.GetString("CounterExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز الدورة.
        /// </summary>
        public static string CourseCode {
            get {
                return ResourceManager.GetString("CourseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الدورة.
        /// </summary>
        public static string CourseLocation {
            get {
                return ResourceManager.GetString("CourseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الدورة.
        /// </summary>
        public static string CourseNumber {
            get {
                return ResourceManager.GetString("CourseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الدورة.
        /// </summary>
        public static string CourseType {
            get {
                return ResourceManager.GetString("CourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء النمودج بنجاح.
        /// </summary>
        public static string createFromExam {
            get {
                return ResourceManager.GetString("createFromExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة البيانات.
        /// </summary>
        public static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ آخر ترقية.
        /// </summary>
        public static string DateLastPromotion {
            get {
                return ResourceManager.GetString("DateLastPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعيين.
        /// </summary>
        public static string DateStartWork {
            get {
                return ResourceManager.GetString("DateStartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة السؤال.
        /// </summary>
        public static string DegreeQuestion {
            get {
                return ResourceManager.GetString("DegreeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم القسم.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم الرئيسي.
        /// </summary>
        public static string DepartmentParent {
            get {
                return ResourceManager.GetString("DepartmentParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدة.
        /// </summary>
        public static string DivisionId {
            get {
                return ResourceManager.GetString("DivisionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الوحدة.
        /// </summary>
        public static string DivisionName {
            get {
                return ResourceManager.GetString("DivisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية هجري.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاختبار.
        /// </summary>
        public static string Exam {
            get {
                return ResourceManager.GetString("Exam", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to لجان الاختبارات.
        /// </summary>
        public static string ExamStudent
        {
            get
            {
                return ResourceManager.GetString("GetExams", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to لجان الاختبارات.
        /// </summary>
        public static string AffectCommittee
        {
            get
            {
                return ResourceManager.GetString("AffectCommittee", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to اسم النموذج.
        /// </summary>
        public static string ExamForm {
            get {
                return ResourceManager.GetString("ExamForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق .
        /// </summary>
        public static string FinalApprove {
            get {
                return ResourceManager.GetString("FinalApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القوة.
        /// </summary>
        public static string ForceId {
            get {
                return ResourceManager.GetString("ForceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم القوة.
        /// </summary>
        public static string ForceName {
            get {
                return ResourceManager.GetString("ForceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرتبة.
        /// </summary>
        public static string GradeName {
            get {
                return ResourceManager.GetString("GradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جناح مساعدات التدريب.
        /// </summary>
        public static string HelpTraining {
            get {
                return ResourceManager.GetString("HelpTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإضافة.
        /// </summary>
        public static string JoinDate {
            get {
                return ResourceManager.GetString("JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر تسجيل دخول.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستوى السؤال.
        /// </summary>
        public static string LevelTypeQuestion {
            get {
                return ResourceManager.GetString("LevelTypeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة صلاحية لمستخدم.
        /// </summary>
        public static string LinkRoleToAccount {
            get {
                return ResourceManager.GetString("LinkRoleToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد مرات تسجيل الدخول.
        /// </summary>
        public static string Logins {
            get {
                return ResourceManager.GetString("Logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة.
        /// </summary>
        public static string manage {
            get {
                return ResourceManager.GetString("manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الدورة.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البنك.
        /// </summary>
        public static string NameBanks {
            get {
                return ResourceManager.GetString("NameBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مفعل.
        /// </summary>
        public static string non_active {
            get {
                return ResourceManager.GetString("non-active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد المقاعد كحد أعلى.
        /// </summary>
        public static string NumberOfSeatsMax {
            get {
                return ResourceManager.GetString("NumberOfSeatsMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد المقاعد كحد أدنى.
        /// </summary>
        public static string NumberOfSeatsMin {
            get {
                return ResourceManager.GetString("NumberOfSeatsMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأسابيع.
        /// </summary>
        public static string NumberOfWeeks {
            get {
                return ResourceManager.GetString("NumberOfWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفترة.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحية.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الخاص.
        /// </summary>
        public static string PrivateNumber {
            get {
                return ResourceManager.GetString("PrivateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص السؤال.
        /// </summary>
        public static string QuestionName {
            get {
                return ResourceManager.GetString("QuestionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسئلة.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط الدورة حقل إجباري.
        /// </summary>
        public static string requirement {
            get {
                return ResourceManager.GetString("requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم مجموعة الصلاحيات.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاحيات المجموعات.
        /// </summary>
        public static string RolesPermissions {
            get {
                return ResourceManager.GetString("RolesPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص.
        /// </summary>
        public static string SpecialityName {
            get {
                return ResourceManager.GetString("SpecialityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البداية هجري.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الحساب.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصاب المعلم.
        /// </summary>
        public static string TeachingHours {
            get {
                return ResourceManager.GetString("TeachingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان السؤال.
        /// </summary>
        public static string TitleQuestion {
            get {
                return ResourceManager.GetString("TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السلاح.
        /// </summary>
        public static string TrainingLocationId {
            get {
                return ResourceManager.GetString("TrainingLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعات الصلاحيات.
        /// </summary>
        public static string UsersRoles {
            get {
                return ResourceManager.GetString("UsersRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفع شعار السلاح.
        /// </summary>
        public static string WeaponImg {
            get {
                return ResourceManager.GetString("WeaponImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم السلاح.
        /// </summary>
        public static string WeaponName {
            get {
                return ResourceManager.GetString("WeaponName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام الترشيح.
        /// </summary>
        public static string WebApi {
            get {
                return ResourceManager.GetString("WebApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العام التدريبي.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
