// ***********************************************************************
// Assembly         : Edu
// Author           : Ali Aljarrah && Walid Azouzi
// Created          : 02-23-2020
//
// Last Modified By : Ali Aljarrah && Walid Azouzi
// Last Modified On : 10-14-2019
// ***********************************************************************
// <copyright file="San_Resource.Designer.cs" company="Expert Systems">
//     Copyright ©  2019
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace Edu.Ressources {
    using System;


    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class San_Resource {

        /// <summary>
        /// The resource man
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// The resource culture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="San_Resource"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public San_Resource() {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <value>The resource manager.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edu.Ressources.San_Resource", typeof(San_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        /// <value>The culture.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to مقدار الحسم نشاط.
        /// </summary>
        /// <value>The amount activity.</value>
        public static string amount_Activity {
            get {
                return ResourceManager.GetString("amount_Activity", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to مقدار حسم السلوك.
        /// </summary>
        /// <value>The amount behavior.</value>
        public static string amount_Behavior {
            get {
                return ResourceManager.GetString("amount_Behavior", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to مقدار حسم المواظبة.
        /// </summary>
        /// <value>The amount perseverance.</value>
        public static string amount_perseverance {
            get {
                return ResourceManager.GetString("amount_perseverance", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ترتيب المخالفة.
        /// </summary>
        /// <value>The arrange infraction.</value>
        public static string Arrange_Infraction {
            get {
                return ResourceManager.GetString("Arrange_Infraction", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to توقيف.
        /// </summary>
        /// <value>The arrest.</value>
        public static string Arrest {
            get {
                return ResourceManager.GetString("Arrest", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to الجزاءالاداري.
        /// </summary>
        /// <value>The arrest admin penalty.</value>
        public static string Arrest_AdminPenalty {
            get {
                return ResourceManager.GetString("Arrest_AdminPenalty", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to توقيف ثابت.
        /// </summary>
        /// <value>The arrest fix.</value>
        public static string Arrest_Fix {
            get {
                return ResourceManager.GetString("Arrest_Fix", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to عدد ايام التوقيف.
        /// </summary>
        /// <value>The arrest hours.</value>
        public static string Arrest_Hours {
            get {
                return ResourceManager.GetString("Arrest_Hours", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to اعادة التوقيف.
        /// </summary>
        /// <value>The arrest repeat.</value>
        public static string Arrest_Repeat {
            get {
                return ResourceManager.GetString("Arrest_Repeat", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to تعهد.
        /// </summary>
        /// <value>The assure.</value>
        public static string Assure {
            get {
                return ResourceManager.GetString("Assure", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to رمز جهة التعهد.
        /// </summary>
        /// <value>The assure user identifier.</value>
        public static string Assure_UserID {
            get {
                return ResourceManager.GetString("Assure_UserID", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to الغاء الدوره.
        /// </summary>
        /// <value>The cancel.</value>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to رقم مادة الغاء الدوره.
        /// </summary>
        /// <value>The cancel materal identifier.</value>
        public static string Cancel_MateralID {
            get {
                return ResourceManager.GetString("Cancel_MateralID", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to رقم فقرة الغاء الدوره.
        /// </summary>
        /// <value>The cancel nu.</value>
        public static string Cancel_nu {
            get {
                return ResourceManager.GetString("Cancel_nu", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to رقم بند الغاء الدوره.
        /// </summary>
        /// <value>The cancel nu1.</value>
        public static string Cancel_nu1 {
            get {
                return ResourceManager.GetString("Cancel_nu1", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to رمز جهة الالغاء.
        /// </summary>
        /// <value>The cancel user identifier.</value>
        public static string Cancel_UserID {
            get {
                return ResourceManager.GetString("Cancel_UserID", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to رمز المخالفة.
        /// </summary>
        /// <value>The code sanction.</value>
        public static string code_Sanction {
            get {
                return ResourceManager.GetString("code_Sanction", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to حسم نشاط.
        /// </summary>
        /// <value>The dis activity.</value>
        public static string dis_Activity {
            get {
                return ResourceManager.GetString("dis_Activity", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to حسم نشاط ثابت.
        /// </summary>
        /// <value>The dis activity fix.</value>
        public static string dis_Activity_fix {
            get {
                return ResourceManager.GetString("dis_Activity_fix", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to حسم سلوك.
        /// </summary>
        /// <value>The dis behavior.</value>
        public static string dis_Behavior {
            get {
                return ResourceManager.GetString("dis_Behavior", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to خسم سلوك ثابت.
        /// </summary>
        /// <value>The dis behavior fix.</value>
        public static string dis_Behavior_fix {
            get {
                return ResourceManager.GetString("dis_Behavior_fix", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to عدد ايام الحسم.
        /// </summary>
        /// <value>The dis day.</value>
        public static string dis_day {
            get {
                return ResourceManager.GetString("dis_day", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to حسم مواظبة.
        /// </summary>
        /// <value>The dis perseverance.</value>
        public static string dis_perseverance {
            get {
                return ResourceManager.GetString("dis_perseverance", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to حسم مرتب.
        /// </summary>
        /// <value>The dis salary.</value>
        public static string dis_salary {
            get {
                return ResourceManager.GetString("dis_salary", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to حسم مرتب ثابت.
        /// </summary>
        /// <value>The dis salary fix.</value>
        public static string dis_salary_fix {
            get {
                return ResourceManager.GetString("dis_salary_fix", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to حسم مواظبة ثابت.
        /// </summary>
        /// <value>The fix perseverance.</value>
        public static string fix_perseverance {
            get {
                return ResourceManager.GetString("fix_perseverance", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to معرف المخالفة.
        /// </summary>
        /// <value>The identifier sactions.</value>
        public static string Id_Sactions {
            get {
                return ResourceManager.GetString("Id_Sactions", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to درجة الحسم.
        /// </summary>
        /// <value>The materials dis ratio.</value>
        public static string Materials__DisRatio {
            get {
                return ResourceManager.GetString("Materials__DisRatio", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to حرمان الماده.
        /// </summary>
        /// <value>The materials deprivation.</value>
        public static string Materials_deprivation {
            get {
                return ResourceManager.GetString("Materials_deprivation", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to قيمة الحرمان.
        /// </summary>
        /// <value>The materials deprivation value.</value>
        public static string Materials_deprivationValue {
            get {
                return ResourceManager.GetString("Materials_deprivationValue", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to حسم درجات الماده.
        /// </summary>
        /// <value>The materials dis degree.</value>
        public static string Materials_DisDegree {
            get {
                return ResourceManager.GetString("Materials_DisDegree", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to مسمى المخالفة.
        /// </summary>
        /// <value>The name infraction.</value>
        public static string name_Infraction {
            get {
                return ResourceManager.GetString("name_Infraction", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ملاحظات.
        /// </summary>
        /// <value>The notes.</value>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to تكرار المخالفة.
        /// </summary>
        /// <value>The rep infraction.</value>
        public static string Rep_Infraction {
            get {
                return ResourceManager.GetString("Rep_Infraction", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to نوع المخالفه.
        /// </summary>
        /// <value>The san category identifier.</value>
        public static string San_CategoryID {
            get {
                return ResourceManager.GetString("San_CategoryID", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to نظام حسم النشاط.
        /// </summary>
        /// <value>The system activity.</value>
        public static string system_Activity {
            get {
                return ResourceManager.GetString("system_Activity", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to نظام حسم السلوك.
        /// </summary>
        /// <value>The system behavior.</value>
        public static string system_Behavior {
            get {
                return ResourceManager.GetString("system_Behavior", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to نظام حسم المواظبة.
        /// </summary>
        /// <value>The system perseverance.</value>
        public static string system_perseverance {
            get {
                return ResourceManager.GetString("system_perseverance", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to انذار.
        /// </summary>
        /// <value>The warrning.</value>
        public static string Warrning {
            get {
                return ResourceManager.GetString("Warrning", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to رمز جهة الانذار.
        /// </summary>
        /// <value>The warrning user identifier.</value>
        public static string Warrning_UserID {
            get {
                return ResourceManager.GetString("Warrning_UserID", resourceCulture);
            }
        }
    }
}
